console.log('linha 0');
console.log('linha 1');
console.log('linha 2');
console.log('linha 3');
console.log('linha 4');
console.log('linha 5');

console.log('-----------------------------------------------------------------------------------------')
// aqui eu faço a mesma coisa de cima porém muito mais facil e rápido


//       1       2     3
for (let i = 0;i <= 5; i++){
    console.log(`linha ${i}`);
}
//1 colocamos primeiro o valor da variavel
//2 o javascript vai repetir o codigo ate a condição ficar falsa
//3 depois incrementa mais um comando
